#if !canImport(ObjectiveC)
import XCTest

extension BeamsViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeamsViewTests = [
        ("testBeamAngledDown", testBeamAngledDown),
        ("testBeamAngledUp", testBeamAngledUp),
        ("testBeamsAndBeamletsWithBeaming", testBeamsAndBeamletsWithBeaming),
        ("testBeamsAndBeamletsWithBeaming2", testBeamsAndBeamletsWithBeaming2),
        ("testBeamsAngledDown", testBeamsAngledDown),
        ("testBeamsAngledDownWithBeaming", testBeamsAngledDownWithBeaming),
        ("testBeamsAngledUp", testBeamsAngledUp),
        ("testBeamsAngledUpWithBeaming", testBeamsAngledUpWithBeaming),
        ("testBeamsStraight", testBeamsStraight),
        ("testBeamsStraightWithBeaming", testBeamsStraightWithBeaming),
        ("testBeamStraight", testBeamStraight),
        ("testBeamStraightWithBeaming", testBeamStraightWithBeaming),
        ("testBeamsWithRhythm", testBeamsWithRhythm),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BeamsViewTests.__allTests__BeamsViewTests),
    ]
}
#endif
