#if !canImport(ObjectiveC)
import XCTest

extension AccidentalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccidentalTests = [
        ("testAccidentalsRender", testAccidentalsRender),
    ]
}

extension ClefTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClefTests = [
        ("testClefsRender", testClefsRender),
    ]
}

extension NoteheadTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteheadTests = [
        ("testNotehead", testNotehead),
    ]
}

extension StaffViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StaffViewTests = [
        ("testStaffLinesAndClef", testStaffLinesAndClef),
        ("testStaffWithLinesNoteheadsAndClef", testStaffWithLinesNoteheadsAndClef),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccidentalTests.__allTests__AccidentalTests),
        testCase(ClefTests.__allTests__ClefTests),
        testCase(NoteheadTests.__allTests__NoteheadTests),
        testCase(StaffViewTests.__allTests__StaffViewTests),
    ]
}
#endif
