#if !canImport(ObjectiveC)
import XCTest

extension ScoreViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScoreViewTests = [
        ("testScoreView", testScoreView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ScoreViewTests.__allTests__ScoreViewTests),
    ]
}
#endif
